import type { Metadata } from 'next';

import { ReactNode } from 'react';

import './globals.css';
import { Header } from '@/app/_components';

import { Providers } from './providers';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <link href="/warchive_favicon.png" rel="icon" type="image/png" />
      <body className="min-h-screen w-full">
        <Providers>
          <div className="mx-auto max-w-5xl sm:px-6 lg:px-8">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
