import type { Metadata } from 'next';

import { ReactNode } from 'react';

import { Providers } from './providers';
import './globals.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full">
        <Providers>
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
